### ISSUE TITLE
Access to code and data

### ISSUE THREAD

**Issue by taiamiti** [hkust-vgd/CoralSCOP#1]
Hello, 

Thank you for the great work, I was wondering when the code and models will be available to test it on my own data. I have seen you have a demo online but I want to port your work into CVAT if possible. Thank you!

**Comment by zhengziqiang** [comment]
Sorry for our late reply. We have recently been busy with data cleaning (removing some coral reef images with copyright issues). At the end of this month, we will release our model (Vit-B model) and the cleaned training data.

**Comment by zhengziqiang** [comment]
Already make the model and data available at https://github.com/zhengziqiang/CoralSCOP.

**Comment by zhengziqiang** [comment]
We have developed a coral reef labeling and analysis tool based on CoralSCOP, which could heavily promote the coral reef labeling and analysis efficiency. Please refer to https://arxiv.org/html/2410.20436v1 for more details.
